/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_datastruct;

import java.io.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darell
 */
public class AdminSystem extends javax.swing.JFrame {

    /**
     * Creates new form AdminSystem
     */
    public AdminSystem() {
        initComponents();
    }

    private void fileWrite() {
        String filePath = "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\Admin_Orders.txt";
        File file = new File(filePath);

        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < this.jTableOrders.getRowCount(); i++) {
                for (int j = 0; j < this.jTableOrders.getColumnCount(); j++) {
                    bw.write(this.jTableOrders.getValueAt(i, j).toString() + " ");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();

        } catch (Exception e) {
        }

    }

    private void fileRead() {
        String filePath = "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\Admin_Orders.txt";
        File file = new File(filePath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) this.jTableOrders.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }

            br.close();
            fr.close();

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name23 = new javax.swing.JLabel();
        Name24 = new javax.swing.JLabel();
        Name25 = new javax.swing.JLabel();
        Name26 = new javax.swing.JLabel();
        Name27 = new javax.swing.JLabel();
        Name28 = new javax.swing.JLabel();
        Name29 = new javax.swing.JLabel();
        choice4 = new java.awt.Choice();
        choice6 = new java.awt.Choice();
        Name37 = new javax.swing.JLabel();
        Name38 = new javax.swing.JLabel();
        Name39 = new javax.swing.JLabel();
        Name40 = new javax.swing.JLabel();
        Name41 = new javax.swing.JLabel();
        Name42 = new javax.swing.JLabel();
        Name43 = new javax.swing.JLabel();
        adminbg = new javax.swing.JPanel();
        adminform = new javax.swing.JPanel();
        adminlogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admindata = new javax.swing.JPanel();
        admindataform = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jbInventory = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jbShipOut = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        lbOrders = new javax.swing.JLabel();
        lblOrderLogo = new javax.swing.JLabel();

        Name23.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name23.setForeground(new java.awt.Color(102, 102, 102));
        Name23.setText("date");

        Name24.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name24.setForeground(new java.awt.Color(102, 102, 102));
        Name24.setText("name");

        Name25.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name25.setForeground(new java.awt.Color(102, 102, 102));
        Name25.setText("order id");

        Name26.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name26.setForeground(new java.awt.Color(102, 102, 102));
        Name26.setText("product");

        Name27.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name27.setForeground(new java.awt.Color(102, 102, 102));
        Name27.setText("0");

        Name28.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name28.setForeground(new java.awt.Color(102, 102, 102));
        Name28.setText("0");

        Name29.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name29.setForeground(new java.awt.Color(102, 102, 102));
        Name29.setText("0");

        Name37.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name37.setForeground(new java.awt.Color(102, 102, 102));
        Name37.setText("0");

        Name38.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name38.setForeground(new java.awt.Color(102, 102, 102));
        Name38.setText("0");

        Name39.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name39.setForeground(new java.awt.Color(102, 102, 102));
        Name39.setText("0");

        Name40.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name40.setForeground(new java.awt.Color(102, 102, 102));
        Name40.setText("product");

        Name41.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name41.setForeground(new java.awt.Color(102, 102, 102));
        Name41.setText("order id");

        Name42.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name42.setForeground(new java.awt.Color(102, 102, 102));
        Name42.setText("name");

        Name43.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name43.setForeground(new java.awt.Color(102, 102, 102));
        Name43.setText("date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orders");

        adminbg.setBackground(new java.awt.Color(204, 204, 204));

        adminform.setBackground(new java.awt.Color(255, 255, 255));

        adminlogo.setBackground(new java.awt.Color(0, 0, 102));
        adminlogo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        adminlogo.setForeground(new java.awt.Color(51, 51, 51));
        adminlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        adminlogo.setText("UAAP CONCEPT STORE");

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Log out");
        jButton1.setBorder(null);

        javax.swing.GroupLayout adminformLayout = new javax.swing.GroupLayout(adminform);
        adminform.setLayout(adminformLayout);
        adminformLayout.setHorizontalGroup(
            adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        adminformLayout.setVerticalGroup(
            adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminformLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminlogo)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        admindata.setBackground(new java.awt.Color(255, 255, 255));

        admindataform.setBackground(new java.awt.Color(255, 255, 255));

        jTableOrders.setBackground(new java.awt.Color(204, 204, 204));
        jTableOrders.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        jTableOrders.setForeground(new java.awt.Color(0, 0, 0));
        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Name", "Date", "Product", "Price", "Quantity", "Total", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTableOrders);

        jbInventory.setBackground(new java.awt.Color(255, 255, 102));
        jbInventory.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbInventory.setForeground(new java.awt.Color(102, 102, 102));
        jbInventory.setText("Inventory");
        jbInventory.setBorder(null);
        jbInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInventoryActionPerformed(evt);
            }
        });

        jbRefresh.setBackground(new java.awt.Color(255, 255, 102));
        jbRefresh.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbRefresh.setForeground(new java.awt.Color(102, 102, 102));
        jbRefresh.setText("Refresh");
        jbRefresh.setBorder(null);
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        jbShipOut.setBackground(new java.awt.Color(255, 255, 102));
        jbShipOut.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbShipOut.setForeground(new java.awt.Color(102, 102, 102));
        jbShipOut.setText("Ship Out");
        jbShipOut.setBorder(null);
        jbShipOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShipOutActionPerformed(evt);
            }
        });

        jbUpdate.setBackground(new java.awt.Color(255, 255, 102));
        jbUpdate.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(102, 102, 102));
        jbUpdate.setText("Update");
        jbUpdate.setBorder(null);
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        lbOrders.setFont(new java.awt.Font("Open Sans Extrabold", 1, 24)); // NOI18N
        lbOrders.setForeground(new java.awt.Color(51, 51, 51));
        lbOrders.setText("Orders");

        lblOrderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/truck.png"))); // NOI18N

        javax.swing.GroupLayout admindataformLayout = new javax.swing.GroupLayout(admindataform);
        admindataform.setLayout(admindataformLayout);
        admindataformLayout.setHorizontalGroup(
            admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admindataformLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbShipOut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(admindataformLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(admindataformLayout.createSequentialGroup()
                        .addComponent(lblOrderLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admindataformLayout.setVerticalGroup(
            admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindataformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbShipOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout admindataLayout = new javax.swing.GroupLayout(admindata);
        admindata.setLayout(admindataLayout);
        admindataLayout.setHorizontalGroup(
            admindataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admindataform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        admindataLayout.setVerticalGroup(
            admindataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindataLayout.createSequentialGroup()
                .addComponent(admindataform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminbgLayout = new javax.swing.GroupLayout(adminbg);
        adminbg.setLayout(adminbgLayout);
        adminbgLayout.setHorizontalGroup(
            adminbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admindata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        adminbgLayout.setVerticalGroup(
            adminbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminbgLayout.createSequentialGroup()
                .addComponent(adminform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admindata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInventoryActionPerformed
        new AdminInventory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbInventoryActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        
        fileRead();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUpdateActionPerformed

    private void jbShipOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShipOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbShipOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name23;
    private javax.swing.JLabel Name24;
    private javax.swing.JLabel Name25;
    private javax.swing.JLabel Name26;
    private javax.swing.JLabel Name27;
    private javax.swing.JLabel Name28;
    private javax.swing.JLabel Name29;
    private javax.swing.JLabel Name37;
    private javax.swing.JLabel Name38;
    private javax.swing.JLabel Name39;
    private javax.swing.JLabel Name40;
    private javax.swing.JLabel Name41;
    private javax.swing.JLabel Name42;
    private javax.swing.JLabel Name43;
    private javax.swing.JPanel adminbg;
    private javax.swing.JPanel admindata;
    private javax.swing.JPanel admindataform;
    private javax.swing.JPanel adminform;
    private javax.swing.JLabel adminlogo;
    private java.awt.Choice choice4;
    private java.awt.Choice choice6;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JButton jbInventory;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbShipOut;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JLabel lbOrders;
    private javax.swing.JLabel lblOrderLogo;
    // End of variables declaration//GEN-END:variables
}
