/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_datastruct;

import java.io.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darell
 */
public class AdminInventory extends javax.swing.JFrame {

    /**
     * Creates new form AdminSystem
     */
    public AdminInventory() {
        initComponents();
        fileRead();
    }

    private void fileWrite() {
        String filePath = "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\Item_Inventory.txt";
        File file = new File(filePath);

        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < this.jTableInventory.getRowCount(); i++) {
                for (int j = 0; j < this.jTableInventory.getColumnCount(); j++) {
                    bw.write(this.jTableInventory.getValueAt(i, j).toString() + " ");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();

        } catch (Exception e) {
        }

    }

    private void fileRead() {
        String filePath = "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\Item_Inventory.txt";
        File file = new File(filePath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) this.jTableInventory.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }

            br.close();
            fr.close();

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name23 = new javax.swing.JLabel();
        Name24 = new javax.swing.JLabel();
        Name25 = new javax.swing.JLabel();
        Name26 = new javax.swing.JLabel();
        Name27 = new javax.swing.JLabel();
        Name28 = new javax.swing.JLabel();
        Name29 = new javax.swing.JLabel();
        choice4 = new java.awt.Choice();
        choice6 = new java.awt.Choice();
        Name37 = new javax.swing.JLabel();
        Name38 = new javax.swing.JLabel();
        Name39 = new javax.swing.JLabel();
        Name40 = new javax.swing.JLabel();
        Name41 = new javax.swing.JLabel();
        Name42 = new javax.swing.JLabel();
        Name43 = new javax.swing.JLabel();
        adminbg = new javax.swing.JPanel();
        adminform = new javax.swing.JPanel();
        adminlogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admindata = new javax.swing.JPanel();
        admindataform = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInventory = new javax.swing.JTable();
        jbtnBack = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        lblInventory = new javax.swing.JLabel();
        lblOrderLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblInventory1 = new javax.swing.JLabel();
        lblInventory2 = new javax.swing.JLabel();
        lblInventory3 = new javax.swing.JLabel();
        lblInventory4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        Name23.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name23.setForeground(new java.awt.Color(102, 102, 102));
        Name23.setText("date");

        Name24.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name24.setForeground(new java.awt.Color(102, 102, 102));
        Name24.setText("name");

        Name25.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name25.setForeground(new java.awt.Color(102, 102, 102));
        Name25.setText("order id");

        Name26.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name26.setForeground(new java.awt.Color(102, 102, 102));
        Name26.setText("product");

        Name27.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name27.setForeground(new java.awt.Color(102, 102, 102));
        Name27.setText("0");

        Name28.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name28.setForeground(new java.awt.Color(102, 102, 102));
        Name28.setText("0");

        Name29.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name29.setForeground(new java.awt.Color(102, 102, 102));
        Name29.setText("0");

        Name37.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name37.setForeground(new java.awt.Color(102, 102, 102));
        Name37.setText("0");

        Name38.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name38.setForeground(new java.awt.Color(102, 102, 102));
        Name38.setText("0");

        Name39.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name39.setForeground(new java.awt.Color(102, 102, 102));
        Name39.setText("0");

        Name40.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name40.setForeground(new java.awt.Color(102, 102, 102));
        Name40.setText("product");

        Name41.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name41.setForeground(new java.awt.Color(102, 102, 102));
        Name41.setText("order id");

        Name42.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name42.setForeground(new java.awt.Color(102, 102, 102));
        Name42.setText("name");

        Name43.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Name43.setForeground(new java.awt.Color(102, 102, 102));
        Name43.setText("date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");

        adminbg.setBackground(new java.awt.Color(204, 204, 204));

        adminform.setBackground(new java.awt.Color(255, 255, 255));

        adminlogo.setBackground(new java.awt.Color(0, 0, 102));
        adminlogo.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        adminlogo.setForeground(new java.awt.Color(51, 51, 51));
        adminlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        adminlogo.setText("UAAP CONCEPT STORE");

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Log out");
        jButton1.setBorder(null);

        javax.swing.GroupLayout adminformLayout = new javax.swing.GroupLayout(adminform);
        adminform.setLayout(adminformLayout);
        adminformLayout.setHorizontalGroup(
            adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        adminformLayout.setVerticalGroup(
            adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminformLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(adminformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminlogo)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        admindata.setBackground(new java.awt.Color(255, 255, 255));

        admindataform.setBackground(new java.awt.Color(255, 255, 255));

        jTableInventory.setBackground(new java.awt.Color(204, 204, 204));
        jTableInventory.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTableInventory.setForeground(new java.awt.Color(0, 0, 0));
        jTableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Stocks"
            }
        ));
        jScrollPane2.setViewportView(jTableInventory);
        if (jTableInventory.getColumnModel().getColumnCount() > 0) {
            jTableInventory.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTableInventory.getColumnModel().getColumn(2).setPreferredWidth(7);
            jTableInventory.getColumnModel().getColumn(3).setPreferredWidth(7);
        }

        jbtnBack.setBackground(new java.awt.Color(255, 255, 102));
        jbtnBack.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(102, 102, 102));
        jbtnBack.setText("Back");
        jbtnBack.setBorder(null);
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbUpdate.setBackground(new java.awt.Color(255, 255, 102));
        jbUpdate.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(102, 102, 102));
        jbUpdate.setText("Update");
        jbUpdate.setBorder(null);
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        lblInventory.setFont(new java.awt.Font("Open Sans Extrabold", 1, 24)); // NOI18N
        lblInventory.setForeground(new java.awt.Color(51, 51, 51));
        lblInventory.setText("Inventory");

        lblOrderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/t-shirt.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblInventory1.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblInventory1.setForeground(new java.awt.Color(51, 51, 51));
        lblInventory1.setText("ID");

        lblInventory2.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblInventory2.setForeground(new java.awt.Color(51, 51, 51));
        lblInventory2.setText("Name");

        lblInventory3.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblInventory3.setForeground(new java.awt.Color(51, 51, 51));
        lblInventory3.setText("Price");

        lblInventory4.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblInventory4.setForeground(new java.awt.Color(51, 51, 51));
        lblInventory4.setText("Stocks");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInventory4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInventory2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInventory3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventory2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventory3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventory4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout admindataformLayout = new javax.swing.GroupLayout(admindataform);
        admindataform.setLayout(admindataformLayout);
        admindataformLayout.setHorizontalGroup(
            admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindataformLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admindataformLayout.createSequentialGroup()
                        .addComponent(lblOrderLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(admindataformLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admindataformLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        admindataformLayout.setVerticalGroup(
            admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindataformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(admindataformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout admindataLayout = new javax.swing.GroupLayout(admindata);
        admindata.setLayout(admindataLayout);
        admindataLayout.setHorizontalGroup(
            admindataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admindataform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        admindataLayout.setVerticalGroup(
            admindataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admindataLayout.createSequentialGroup()
                .addComponent(admindataform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminbgLayout = new javax.swing.GroupLayout(adminbg);
        adminbg.setLayout(adminbgLayout);
        adminbgLayout.setHorizontalGroup(
            adminbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admindata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        adminbgLayout.setVerticalGroup(
            adminbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminbgLayout.createSequentialGroup()
                .addComponent(adminform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admindata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        new AdminSystem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUpdateActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new AdminInventory().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name23;
    private javax.swing.JLabel Name24;
    private javax.swing.JLabel Name25;
    private javax.swing.JLabel Name26;
    private javax.swing.JLabel Name27;
    private javax.swing.JLabel Name28;
    private javax.swing.JLabel Name29;
    private javax.swing.JLabel Name37;
    private javax.swing.JLabel Name38;
    private javax.swing.JLabel Name39;
    private javax.swing.JLabel Name40;
    private javax.swing.JLabel Name41;
    private javax.swing.JLabel Name42;
    private javax.swing.JLabel Name43;
    private javax.swing.JPanel adminbg;
    private javax.swing.JPanel admindata;
    private javax.swing.JPanel admindataform;
    private javax.swing.JPanel adminform;
    private javax.swing.JLabel adminlogo;
    private java.awt.Choice choice4;
    private java.awt.Choice choice6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableInventory;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblInventory1;
    private javax.swing.JLabel lblInventory2;
    private javax.swing.JLabel lblInventory3;
    private javax.swing.JLabel lblInventory4;
    private javax.swing.JLabel lblOrderLogo;
    // End of variables declaration//GEN-END:variables
}
