/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_datastruct;

/**
 *
 * @author Darell, Cyrus, Vince
 */
public class HomePage extends javax.swing.JFrame {
    
    
    public HomePage() {
        super("Home");
        initComponents();
    }

    public HomePage(String fullName) {
        super("Home");
        initComponents();

        Accntbtn.setText(fullName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MenuBar1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Background = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnUnivTee = new javax.swing.JButton();
        BtnLanyards = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnGifts = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menubar = new javax.swing.JPanel();
        Shipmentbtn = new javax.swing.JButton();
        Favbtn = new javax.swing.JButton();
        Cartbtn = new javax.swing.JButton();
        Accntbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        USTshirtbtn = new javax.swing.JButton();
        NUshirtbtn = new javax.swing.JButton();
        FEUshirtbtn = new javax.swing.JButton();
        lblPriceNUtee = new javax.swing.JLabel();
        NUaddc = new javax.swing.JButton();
        FEUbuy = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblPriceFEUtee = new javax.swing.JLabel();
        NUbuy = new javax.swing.JButton();
        FEUaddc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblPriceUSTtee = new javax.swing.JLabel();
        USTbuy = new javax.swing.JButton();
        USTaddc = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        NUheart = new javax.swing.JButton();
        FEUheart = new javax.swing.JButton();
        USTheart = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        MenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        MenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuBar1Layout = new javax.swing.GroupLayout(MenuBar1);
        MenuBar1.setLayout(MenuBar1Layout);
        MenuBar1Layout.setHorizontalGroup(
            MenuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        MenuBar1Layout.setVerticalGroup(
            MenuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Nationalian Tee");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("University Tee");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("NU BULLDOGS TEE");

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 1, 11)); // NOI18N
        jLabel6.setText("Show you support while feeling the 100% cotton ");

        jLabel7.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("UNIVERSITY TEES");
        jLabel7.setFocusCycleRoot(true);
        jLabel7.setFocusTraversalPolicyProvider(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnUnivTee.setBackground(new java.awt.Color(255, 255, 255));
        BtnUnivTee.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        BtnUnivTee.setForeground(new java.awt.Color(51, 51, 51));
        BtnUnivTee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/t-shirt.png"))); // NOI18N
        BtnUnivTee.setText(" University Tee");
        BtnUnivTee.setBorder(null);
        BtnUnivTee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUnivTee.setEnabled(false);
        BtnUnivTee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUnivTeeActionPerformed(evt);
            }
        });

        BtnLanyards.setBackground(new java.awt.Color(255, 255, 255));
        BtnLanyards.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        BtnLanyards.setForeground(new java.awt.Color(51, 51, 51));
        BtnLanyards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/lanyard.png"))); // NOI18N
        BtnLanyards.setText("Lanyards");
        BtnLanyards.setBorder(null);
        BtnLanyards.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnLanyards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLanyardsActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Coming soon");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnGifts.setBackground(new java.awt.Color(255, 255, 255));
        BtnGifts.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        BtnGifts.setForeground(new java.awt.Color(51, 51, 51));
        BtnGifts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/gift.png"))); // NOI18N
        BtnGifts.setText(" Gifts ");
        BtnGifts.setBorder(null);
        BtnGifts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnGifts.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnGifts.setIconTextGap(5);
        BtnGifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGiftsActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 102));
        btnLogOut.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 51, 51));
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnUnivTee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGifts, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLanyards, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(BtnUnivTee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLanyards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGifts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        jLabel13.setText("UAAP CONCEPT STORE");

        menubar.setBackground(new java.awt.Color(255, 255, 255));

        Shipmentbtn.setBackground(new java.awt.Color(255, 255, 255));
        Shipmentbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Shipmentbtn.setForeground(new java.awt.Color(51, 51, 51));
        Shipmentbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/truck.png"))); // NOI18N
        Shipmentbtn.setText("Shipment");
        Shipmentbtn.setBorder(null);
        Shipmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipmentbtnActionPerformed(evt);
            }
        });

        Favbtn.setBackground(new java.awt.Color(255, 255, 255));
        Favbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Favbtn.setForeground(new java.awt.Color(51, 51, 51));
        Favbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        Favbtn.setText("Favorites");
        Favbtn.setBorder(null);
        Favbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavbtnActionPerformed(evt);
            }
        });

        Cartbtn.setBackground(new java.awt.Color(255, 255, 255));
        Cartbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Cartbtn.setForeground(new java.awt.Color(51, 51, 51));
        Cartbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/shopping-cart-empty-side-view.png"))); // NOI18N
        Cartbtn.setText("Cart");
        Cartbtn.setBorder(null);
        Cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartbtnActionPerformed(evt);
            }
        });

        Accntbtn.setBackground(new java.awt.Color(255, 255, 255));
        Accntbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Accntbtn.setForeground(new java.awt.Color(51, 51, 51));
        Accntbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/blank-avatar.png"))); // NOI18N
        Accntbtn.setText("Account");
        Accntbtn.setBorder(null);
        Accntbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Accntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccntbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(Favbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Shipmentbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cartbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Accntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Shipmentbtn)
                    .addComponent(Favbtn)
                    .addComponent(Cartbtn)
                    .addComponent(Accntbtn))
                .addGap(14, 14, 14))
        );

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("             search");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        USTshirtbtn.setBackground(new java.awt.Color(255, 255, 255));
        USTshirtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/USTshirt.png"))); // NOI18N
        USTshirtbtn.setBorder(null);
        USTshirtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTshirtbtnActionPerformed(evt);
            }
        });

        NUshirtbtn.setBackground(new java.awt.Color(255, 255, 255));
        NUshirtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/BulldogShirt.png"))); // NOI18N
        NUshirtbtn.setBorder(null);
        NUshirtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUshirtbtnActionPerformed(evt);
            }
        });

        FEUshirtbtn.setBackground(new java.awt.Color(255, 255, 255));
        FEUshirtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/FEUShirt.png"))); // NOI18N
        FEUshirtbtn.setBorder(null);
        FEUshirtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUshirtbtnActionPerformed(evt);
            }
        });

        lblPriceNUtee.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblPriceNUtee.setForeground(new java.awt.Color(153, 153, 153));
        lblPriceNUtee.setText("P300.00");

        NUaddc.setBackground(new java.awt.Color(255, 255, 255));
        NUaddc.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        NUaddc.setForeground(new java.awt.Color(51, 51, 51));
        NUaddc.setText("Add to Cart");
        NUaddc.setBorder(null);

        FEUbuy.setBackground(new java.awt.Color(255, 255, 102));
        FEUbuy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUbuy.setForeground(new java.awt.Color(51, 51, 51));
        FEUbuy.setText("Buy");
        FEUbuy.setBorder(null);
        FEUbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUbuyActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("TAMARAW TEE");

        lblPriceFEUtee.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblPriceFEUtee.setForeground(new java.awt.Color(153, 153, 153));
        lblPriceFEUtee.setText("P320.00");

        NUbuy.setBackground(new java.awt.Color(255, 255, 102));
        NUbuy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        NUbuy.setForeground(new java.awt.Color(51, 51, 51));
        NUbuy.setText("Buy");
        NUbuy.setBorder(null);
        NUbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUbuyActionPerformed(evt);
            }
        });

        FEUaddc.setBackground(new java.awt.Color(255, 255, 255));
        FEUaddc.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUaddc.setForeground(new java.awt.Color(51, 51, 51));
        FEUaddc.setText("Add to Cart");
        FEUaddc.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("TIGERS TEE");

        lblPriceUSTtee.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblPriceUSTtee.setForeground(new java.awt.Color(153, 153, 153));
        lblPriceUSTtee.setText("P350.00");

        USTbuy.setBackground(new java.awt.Color(255, 255, 102));
        USTbuy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTbuy.setForeground(new java.awt.Color(51, 51, 51));
        USTbuy.setText("Buy");
        USTbuy.setBorder(null);
        USTbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTbuyActionPerformed(evt);
            }
        });

        USTaddc.setBackground(new java.awt.Color(255, 255, 255));
        USTaddc.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTaddc.setForeground(new java.awt.Color(51, 51, 51));
        USTaddc.setText("Add to Cart");
        USTaddc.setBorder(null);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/magnifying-search-lenses-tool.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        NUheart.setBackground(new java.awt.Color(255, 255, 255));
        NUheart.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        NUheart.setForeground(new java.awt.Color(51, 51, 51));
        NUheart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        NUheart.setBorder(null);
        NUheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUheartActionPerformed(evt);
            }
        });

        FEUheart.setBackground(new java.awt.Color(255, 255, 255));
        FEUheart.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUheart.setForeground(new java.awt.Color(51, 51, 51));
        FEUheart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        FEUheart.setBorder(null);
        FEUheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUheartActionPerformed(evt);
            }
        });

        USTheart.setBackground(new java.awt.Color(255, 255, 255));
        USTheart.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTheart.setForeground(new java.awt.Color(51, 51, 51));
        USTheart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        USTheart.setBorder(null);
        USTheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTheartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblPriceNUtee)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NUheart)
                                        .addGap(142, 142, 142)
                                        .addComponent(lblPriceFEUtee)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FEUheart))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(NUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(109, 109, 109)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addComponent(FEUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(106, 106, 106)
                                                .addComponent(USTbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(107, 107, 107)
                                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                                        .addComponent(lblPriceUSTtee)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(USTheart))
                                                    .addComponent(jLabel10)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(NUshirtbtn)
                                        .addGap(72, 72, 72)
                                        .addComponent(FEUshirtbtn)
                                        .addGap(48, 48, 48)
                                        .addComponent(USTshirtbtn)))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(NUaddc)
                        .addGap(152, 152, 152)
                        .addComponent(FEUaddc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(USTaddc)
                        .addGap(121, 121, 121))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel11)
                    .addContainerGap(286, Short.MAX_VALUE)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel12)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton9)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)))
                        .addGap(52, 52, 52)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NUshirtbtn)
                                .addComponent(FEUshirtbtn))
                            .addComponent(USTshirtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriceNUtee)
                            .addComponent(lblPriceFEUtee)
                            .addComponent(lblPriceUSTtee)
                            .addComponent(NUheart)
                            .addComponent(FEUheart)
                            .addComponent(USTheart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FEUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(USTbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NUaddc)
                            .addComponent(FEUaddc)
                            .addComponent(USTaddc))
                        .addContainerGap())))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel11)
                    .addContainerGap(265, Short.MAX_VALUE)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel12)
                    .addContainerGap(265, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUnivTeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUnivTeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUnivTeeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnLanyardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLanyardsActionPerformed
        new Lanyards(this.Accntbtn.getText().toString()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLanyardsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnGiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGiftsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGiftsActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void USTshirtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTshirtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USTshirtbtnActionPerformed

    private void NUshirtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUshirtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUshirtbtnActionPerformed

    private void FEUshirtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUshirtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEUshirtbtnActionPerformed

    private void FEUbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUbuyActionPerformed

        new ShipmentForm(this.Accntbtn.getText(), "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\FEUShirt.png",
        "TAMARAW TEE", lblPriceFEUtee.getText().toString().replace(".00", "")).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FEUbuyActionPerformed

    private void NUbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUbuyActionPerformed

        new ShipmentForm(this.Accntbtn.getText(), "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\BulldogShirt.png",
        "NU BULLDOGS TEE", lblPriceNUtee.getText().toString().replace(".00", "")).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NUbuyActionPerformed

    private void USTbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTbuyActionPerformed

        new ShipmentForm(this.Accntbtn.getText(), "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\USTshirt.png", 
                "TIGERS TEE", lblPriceUSTtee.getText().toString().replace(".00", "")).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_USTbuyActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ShipmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipmentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipmentbtnActionPerformed

    private void FavbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FavbtnActionPerformed

    private void CartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartbtnActionPerformed
        
    }//GEN-LAST:event_CartbtnActionPerformed

    private void AccntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccntbtnActionPerformed
        new ListofOrders(Accntbtn.getText().toString()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccntbtnActionPerformed

    private void NUheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUheartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUheartActionPerformed

    private void FEUheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUheartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEUheartActionPerformed

    private void USTheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTheartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USTheartActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        new LoginSystem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accntbtn;
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnGifts;
    private javax.swing.JButton BtnLanyards;
    private javax.swing.JButton BtnUnivTee;
    private javax.swing.JButton Cartbtn;
    private javax.swing.JButton FEUaddc;
    private javax.swing.JButton FEUbuy;
    private javax.swing.JButton FEUheart;
    private javax.swing.JButton FEUshirtbtn;
    private javax.swing.JButton Favbtn;
    private javax.swing.JPanel MenuBar1;
    private javax.swing.JButton NUaddc;
    private javax.swing.JButton NUbuy;
    private javax.swing.JButton NUheart;
    private javax.swing.JButton NUshirtbtn;
    private javax.swing.JButton Shipmentbtn;
    private javax.swing.JButton USTaddc;
    private javax.swing.JButton USTbuy;
    private javax.swing.JButton USTheart;
    private javax.swing.JButton USTshirtbtn;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPriceFEUtee;
    private javax.swing.JLabel lblPriceNUtee;
    private javax.swing.JLabel lblPriceUSTtee;
    private javax.swing.JPanel menubar;
    // End of variables declaration//GEN-END:variables
}
