/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_datastruct;

/**
 *
 * @author Darell, Cyrus, Vince
 */
public class Lanyards extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public Lanyards() {
        super("Lanyards");
        initComponents();

    }

    public Lanyards(String fullName) {
        super("Lanyards");
        initComponents();

        this.Accntbtn.setText(fullName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menubar2 = new javax.swing.JPanel();
        Favbtn = new javax.swing.JButton();
        Accntbtn = new javax.swing.JButton();
        Shipmentbtn = new javax.swing.JButton();
        Cartbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        USTshirtbtn = new javax.swing.JButton();
        FEUshirtbtn = new javax.swing.JButton();
        FEUbuy = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblFEUlanyard = new javax.swing.JLabel();
        FEUaddc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblUSTlanyard = new javax.swing.JLabel();
        USTbuy = new javax.swing.JButton();
        USTaddc = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        FEUheart = new javax.swing.JButton();
        USTheart = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 1, 11)); // NOI18N
        jLabel6.setText("Show you support by wearing the official UAAP");

        jLabel7.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("UNIVERSITY LANYARDS");
        jLabel7.setFocusCycleRoot(true);
        jLabel7.setFocusTraversalPolicyProvider(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/t-shirt.png"))); // NOI18N
        jButton1.setText(" University Tee");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/lanyard.png"))); // NOI18N
        jButton3.setText("Lanyards");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Coming soon");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/gift.png"))); // NOI18N
        jButton5.setText(" Gifts ");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setIconTextGap(5);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 102));
        btnLogout.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(51, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        jLabel13.setText("UAAP CONCEPT STORE");

        menubar2.setBackground(new java.awt.Color(255, 255, 255));

        Favbtn.setBackground(new java.awt.Color(255, 255, 255));
        Favbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Favbtn.setForeground(new java.awt.Color(51, 51, 51));
        Favbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        Favbtn.setText("Favorites");
        Favbtn.setBorder(null);
        Favbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavbtnActionPerformed(evt);
            }
        });

        Accntbtn.setBackground(new java.awt.Color(255, 255, 255));
        Accntbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Accntbtn.setForeground(new java.awt.Color(51, 51, 51));
        Accntbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/blank-avatar.png"))); // NOI18N
        Accntbtn.setText("Account");
        Accntbtn.setBorder(null);
        Accntbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Accntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccntbtnActionPerformed(evt);
            }
        });

        Shipmentbtn.setBackground(new java.awt.Color(255, 255, 255));
        Shipmentbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Shipmentbtn.setForeground(new java.awt.Color(51, 51, 51));
        Shipmentbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/truck.png"))); // NOI18N
        Shipmentbtn.setText("Shipment");
        Shipmentbtn.setBorder(null);
        Shipmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipmentbtnActionPerformed(evt);
            }
        });

        Cartbtn.setBackground(new java.awt.Color(255, 255, 255));
        Cartbtn.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        Cartbtn.setForeground(new java.awt.Color(51, 51, 51));
        Cartbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/shopping-cart-empty-side-view.png"))); // NOI18N
        Cartbtn.setText("Cart");
        Cartbtn.setBorder(null);
        Cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menubar2Layout = new javax.swing.GroupLayout(menubar2);
        menubar2.setLayout(menubar2Layout);
        menubar2Layout.setHorizontalGroup(
            menubar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Favbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Shipmentbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cartbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Accntbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        menubar2Layout.setVerticalGroup(
            menubar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubar2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(menubar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Shipmentbtn)
                    .addComponent(Favbtn)
                    .addComponent(Cartbtn)
                    .addComponent(Accntbtn))
                .addGap(18, 18, 18))
        );

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("             search");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        USTshirtbtn.setBackground(new java.awt.Color(255, 255, 255));
        USTshirtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/14435388-1404731176223121-3322577590407067022-o_1.jpeg"))); // NOI18N
        USTshirtbtn.setBorder(null);
        USTshirtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTshirtbtnActionPerformed(evt);
            }
        });

        FEUshirtbtn.setBackground(new java.awt.Color(255, 255, 255));
        FEUshirtbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/9df4f340795749.Y3JvcCw3MjMsNTY1LDg4LDcz.jpg"))); // NOI18N
        FEUshirtbtn.setBorder(null);
        FEUshirtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUshirtbtnActionPerformed(evt);
            }
        });

        FEUbuy.setBackground(new java.awt.Color(255, 255, 102));
        FEUbuy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUbuy.setForeground(new java.awt.Color(51, 51, 51));
        FEUbuy.setText("Buy");
        FEUbuy.setBorder(null);
        FEUbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUbuyActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("TAMARAW LANYARD");

        lblFEUlanyard.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblFEUlanyard.setForeground(new java.awt.Color(153, 153, 153));
        lblFEUlanyard.setText("P200.00");

        FEUaddc.setBackground(new java.awt.Color(255, 255, 255));
        FEUaddc.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUaddc.setForeground(new java.awt.Color(51, 51, 51));
        FEUaddc.setText("Add to Cart");
        FEUaddc.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("TIGERS LANYARD");

        lblUSTlanyard.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        lblUSTlanyard.setForeground(new java.awt.Color(153, 153, 153));
        lblUSTlanyard.setText("P250.00");

        USTbuy.setBackground(new java.awt.Color(255, 255, 102));
        USTbuy.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTbuy.setForeground(new java.awt.Color(51, 51, 51));
        USTbuy.setText("Buy");
        USTbuy.setBorder(null);
        USTbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTbuyActionPerformed(evt);
            }
        });

        USTaddc.setBackground(new java.awt.Color(255, 255, 255));
        USTaddc.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTaddc.setForeground(new java.awt.Color(51, 51, 51));
        USTaddc.setText("Add to Cart");
        USTaddc.setBorder(null);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/magnifying-search-lenses-tool.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        FEUheart.setBackground(new java.awt.Color(255, 255, 255));
        FEUheart.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        FEUheart.setForeground(new java.awt.Color(51, 51, 51));
        FEUheart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        FEUheart.setBorder(null);
        FEUheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEUheartActionPerformed(evt);
            }
        });

        USTheart.setBackground(new java.awt.Color(255, 255, 255));
        USTheart.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        USTheart.setForeground(new java.awt.Color(51, 51, 51));
        USTheart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/e-commerce-like-heart.png"))); // NOI18N
        USTheart.setBorder(null);
        USTheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USTheartActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Open Sans Light", 1, 11)); // NOI18N
        jLabel15.setText("University Lanyards");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menubar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(FEUshirtbtn))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(FEUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addComponent(lblFEUlanyard)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FEUheart))))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(FEUaddc)))
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblUSTlanyard)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(USTheart)
                                        .addGap(304, 304, 304))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                        .addComponent(USTshirtbtn)
                                        .addGap(278, 278, 278))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel10))
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(USTbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addComponent(USTaddc)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addContainerGap())))))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel11)
                    .addContainerGap(286, Short.MAX_VALUE)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel12)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menubar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton9)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(FEUshirtbtn)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFEUlanyard)
                                    .addComponent(FEUheart))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FEUbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FEUaddc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addComponent(USTshirtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUSTlanyard)
                                    .addComponent(USTheart))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(USTbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(USTaddc)))
                        .addContainerGap(77, Short.MAX_VALUE))))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel11)
                    .addContainerGap(265, Short.MAX_VALUE)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel12)
                    .addContainerGap(265, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage(Accntbtn.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void USTshirtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTshirtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USTshirtbtnActionPerformed

    private void FEUshirtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUshirtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEUshirtbtnActionPerformed

    private void FEUbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUbuyActionPerformed

        new ShipmentForm(this.Accntbtn.getText().replace(" ", ""), "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\"
                + "9df4f340795749.Y3JvcCw3MjMsNTY1LDg4LDcz.jpg",
                "TAMARAW LANYARD", lblFEUlanyard.getText().replace(".00", "")).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FEUbuyActionPerformed

    private void USTbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTbuyActionPerformed

        new ShipmentForm(this.Accntbtn.getText().replace(" ", ""), "C:\\Users\\HP\\Desktop\\Files(Programming)"
                + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\"
                + "14435388-1404731176223121-3322577590407067022-o_1.jpeg",
                "TIGERS LANYARD", lblUSTlanyard.getText().replace(".00", "")).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_USTbuyActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void FEUheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEUheartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEUheartActionPerformed

    private void USTheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USTheartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USTheartActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        new LoginSystem().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void FavbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FavbtnActionPerformed

    private void ShipmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipmentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipmentbtnActionPerformed

    private void AccntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccntbtnActionPerformed
        new ListofOrders(this.Accntbtn.getText().replace(" ", "")).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccntbtnActionPerformed

    private void CartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartbtnActionPerformed
        
    }//GEN-LAST:event_CartbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanyards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanyards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanyards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanyards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanyards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accntbtn;
    private javax.swing.JPanel Background;
    private javax.swing.JButton Cartbtn;
    private javax.swing.JButton FEUaddc;
    private javax.swing.JButton FEUbuy;
    private javax.swing.JButton FEUheart;
    private javax.swing.JButton FEUshirtbtn;
    private javax.swing.JButton Favbtn;
    private javax.swing.JButton Shipmentbtn;
    private javax.swing.JButton USTaddc;
    private javax.swing.JButton USTbuy;
    private javax.swing.JButton USTheart;
    private javax.swing.JButton USTshirtbtn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFEUlanyard;
    private javax.swing.JLabel lblUSTlanyard;
    private javax.swing.JPanel menubar2;
    // End of variables declaration//GEN-END:variables
}
