/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_datastruct;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Darell, Cyrus, Vince
 */
public class LoginSystem extends javax.swing.JFrame {

    private String userName;
    private String passWord;
    private String fullName;
    private String userType;
    private final int secretCode = 1111;
    private final String filepathAcc = "C:\\Users\\HP\\Desktop\\Files(Programming)"
            + "\\JavaProgramming\\Project_DataStruct\\Project_DataStruct\\src\\project_datastruct\\Accounts.txt";
    private final String alphabeth = "^[a-zA-Z]*$";
    private final String numbers = "(.*[0-9].*)";

    public LoginSystem() {
        super("UAAP Concept Store");
        initComponents();
    }

    private String getFullName() {
        String fullName = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(this.filepathAcc));
            String tempLine;
            String tempUsername;
            String[] acc;

            while ((tempLine = br.readLine()) != null) {
                acc = tempLine.split(",");
                tempUsername = acc[0];

                if (tempUsername.trim().equals(tfUsername.getText())) {
                    fullName = acc[3];
                    break;

                }
            }
            br.close();
        } catch (Exception e) {
            System.out.println("");
        }

        return fullName;
    }


    private void createAcc(String username, String password, String type) {
        FileWriter fw = null;
        PrintWriter pr = null;
        try {
            fw = new FileWriter(this.filepathAcc, true);
            pr = new PrintWriter(fw);

            pr.print(username);
            pr.print(",");
            pr.print(password);
            pr.print(",");
            pr.print(type);
            pr.print(",");
            pr.print(getFullName());

            pr.println("");
            pr.close();
            fw.close();

        } catch (IOException ioe) {
            System.out.println("Creating Acc");
        }

    }

    private boolean verifyLogin(String username, String password, String type) {
        boolean found = false;
        try {
            BufferedReader br = new BufferedReader(new FileReader(this.filepathAcc));
            String tempLine;
            String tempUsername;
            String tempPassword;
            String tempType;
            String[] acc;

            while ((tempLine = br.readLine()) != null) {
                acc = tempLine.split(",");
                tempUsername = acc[0];
                tempPassword = acc[1];
                tempType = acc[2];

                if (tempUsername.trim().equals(username.trim()) && tempPassword.trim().trim().equals(password.trim()) && tempType.trim().equals(type.trim())) {
                    found = true;
                    break;

                }
            }
            br.close();
        } catch (Exception e) {
            System.out.println("Verify Login Error");
        }

        return found;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        FN1 = new javax.swing.JLabel();
        firstname1 = new javax.swing.JTextField();
        Loginbg = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        BtnLoginGoogle = new javax.swing.JButton();
        BtnLoginMicrosoft = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnSignin = new javax.swing.JButton();
        BtnLoginAdmin = new javax.swing.JButton();
        jpSignin = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        RegisterForm = new javax.swing.JPanel();
        Signup = new javax.swing.JLabel();
        tfLastname = new javax.swing.JTextField();
        tfFirstname = new javax.swing.JTextField();
        FN = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        Username1 = new javax.swing.JLabel();
        tfUniversity = new javax.swing.JTextField();
        school = new javax.swing.JLabel();
        tfCourse = new javax.swing.JTextField();
        Username2 = new javax.swing.JLabel();
        tfIDnum = new javax.swing.JTextField();
        IDnumber = new javax.swing.JLabel();
        BtnSignUp = new javax.swing.JButton();
        BtnSignUpAsAdmin = new javax.swing.JButton();
        jpSignUp = new javax.swing.JPasswordField();
        fNameAlert = new javax.swing.JLabel();
        lNameAlert = new javax.swing.JLabel();
        userAlert = new javax.swing.JLabel();
        passAlert = new javax.swing.JLabel();
        univAlert = new javax.swing.JLabel();
        courseAlert = new javax.swing.JLabel();
        IDnumAlert = new javax.swing.JLabel();

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        jLabel13.setText("UAAP CONCEPT STORE");

        FN1.setText("First Name");

        firstname1.setBackground(new java.awt.Color(204, 204, 204));
        firstname1.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        firstname1.setForeground(new java.awt.Color(153, 153, 153));
        firstname1.setBorder(null);
        firstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Loginbg.setBackground(new java.awt.Color(153, 153, 153));

        LoginForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_datastruct/1200px-Logo_of_University_Athletic_Association_of_the_Philippines.svg.png"))); // NOI18N
        jLabel14.setText("UAAP CONCEPT STORE");

        BtnLoginGoogle.setBackground(new java.awt.Color(255, 255, 102));
        BtnLoginGoogle.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnLoginGoogle.setForeground(new java.awt.Color(51, 51, 51));
        BtnLoginGoogle.setText("Log In with Google");
        BtnLoginGoogle.setBorder(null);

        BtnLoginMicrosoft.setBackground(new java.awt.Color(255, 255, 102));
        BtnLoginMicrosoft.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnLoginMicrosoft.setForeground(new java.awt.Color(51, 51, 51));
        BtnLoginMicrosoft.setText("Log In with Microsoft");
        BtnLoginMicrosoft.setBorder(null);

        tfUsername.setBackground(new java.awt.Color(204, 204, 204));
        tfUsername.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(153, 153, 153));
        tfUsername.setText("  Username");
        tfUsername.setBorder(null);
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        jLabel1.setText("forgot password?");

        BtnSignin.setBackground(new java.awt.Color(255, 255, 102));
        BtnSignin.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnSignin.setForeground(new java.awt.Color(51, 51, 51));
        BtnSignin.setText("Sign In");
        BtnSignin.setBorder(null);
        BtnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSigninActionPerformed(evt);
            }
        });

        BtnLoginAdmin.setBackground(new java.awt.Color(255, 255, 102));
        BtnLoginAdmin.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnLoginAdmin.setForeground(new java.awt.Color(51, 51, 51));
        BtnLoginAdmin.setText("Log in as Admin");
        BtnLoginAdmin.setBorder(null);
        BtnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginAdminActionPerformed(evt);
            }
        });

        jpSignin.setBackground(new java.awt.Color(204, 204, 204));
        jpSignin.setForeground(new java.awt.Color(153, 153, 153));
        jpSignin.setText("Password");
        jpSignin.setBorder(null);
        jpSignin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpSigninFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpSigninFocusLost(evt);
            }
        });

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addGroup(LoginFormLayout.createSequentialGroup()
                                .addComponent(BtnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jpSignin)))
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLoginMicrosoft, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLoginGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(BtnLoginMicrosoft, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLoginGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Open Sans Extrabold", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));

        RegisterForm.setBackground(new java.awt.Color(255, 255, 255));
        RegisterForm.setForeground(new java.awt.Color(51, 51, 51));

        Signup.setFont(new java.awt.Font("Open Sans Extrabold", 1, 18)); // NOI18N
        Signup.setForeground(new java.awt.Color(51, 51, 51));
        Signup.setText("Sign Up");

        tfLastname.setBackground(new java.awt.Color(204, 204, 204));
        tfLastname.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfLastname.setForeground(new java.awt.Color(0, 0, 0));
        tfLastname.setBorder(null);
        tfLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastnameActionPerformed(evt);
            }
        });
        tfLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLastnameKeyPressed(evt);
            }
        });

        tfFirstname.setBackground(new java.awt.Color(204, 204, 204));
        tfFirstname.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfFirstname.setForeground(new java.awt.Color(0, 0, 0));
        tfFirstname.setBorder(null);
        tfFirstname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfFirstnameInputMethodTextChanged(evt);
            }
        });
        tfFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstnameActionPerformed(evt);
            }
        });
        tfFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFirstnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFirstnameKeyReleased(evt);
            }
        });

        FN.setText("First Name");

        LN.setText("Last Name");

        Username.setText("Username");

        tfUser.setBackground(new java.awt.Color(204, 204, 204));
        tfUser.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfUser.setForeground(new java.awt.Color(0, 0, 0));
        tfUser.setBorder(null);
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserKeyPressed(evt);
            }
        });

        Username1.setText("Password");

        tfUniversity.setBackground(new java.awt.Color(204, 204, 204));
        tfUniversity.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfUniversity.setForeground(new java.awt.Color(0, 0, 0));
        tfUniversity.setBorder(null);
        tfUniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUniversityActionPerformed(evt);
            }
        });
        tfUniversity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUniversityKeyPressed(evt);
            }
        });

        school.setText("Address");

        tfCourse.setBackground(new java.awt.Color(204, 204, 204));
        tfCourse.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfCourse.setForeground(new java.awt.Color(0, 0, 0));
        tfCourse.setBorder(null);
        tfCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCourseActionPerformed(evt);
            }
        });
        tfCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCourseKeyPressed(evt);
            }
        });

        Username2.setText("School University");

        tfIDnum.setBackground(new java.awt.Color(204, 204, 204));
        tfIDnum.setFont(new java.awt.Font("Open Sans Semibold", 0, 10)); // NOI18N
        tfIDnum.setForeground(new java.awt.Color(0, 0, 0));
        tfIDnum.setBorder(null);
        tfIDnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDnumActionPerformed(evt);
            }
        });
        tfIDnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIDnumKeyPressed(evt);
            }
        });

        IDnumber.setText("Contact Number");

        BtnSignUp.setBackground(new java.awt.Color(255, 255, 102));
        BtnSignUp.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnSignUp.setForeground(new java.awt.Color(51, 51, 51));
        BtnSignUp.setText("Sign Up");
        BtnSignUp.setBorder(null);
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });

        BtnSignUpAsAdmin.setBackground(new java.awt.Color(255, 255, 102));
        BtnSignUpAsAdmin.setFont(new java.awt.Font("Open Sans Extrabold", 1, 12)); // NOI18N
        BtnSignUpAsAdmin.setForeground(new java.awt.Color(51, 51, 51));
        BtnSignUpAsAdmin.setText("Sign Up as Admin");
        BtnSignUpAsAdmin.setBorder(null);
        BtnSignUpAsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpAsAdminActionPerformed(evt);
            }
        });

        jpSignUp.setBackground(new java.awt.Color(204, 204, 204));
        jpSignUp.setForeground(new java.awt.Color(0, 0, 0));
        jpSignUp.setBorder(null);
        jpSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpSignUpKeyPressed(evt);
            }
        });

        fNameAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        fNameAlert.setText("       ");

        lNameAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lNameAlert.setText("       ");

        userAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        userAlert.setText("       ");

        passAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        passAlert.setText("       ");

        univAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        univAlert.setText("       ");

        courseAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        courseAlert.setText("       ");

        IDnumAlert.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        IDnumAlert.setText("       ");

        javax.swing.GroupLayout RegisterFormLayout = new javax.swing.GroupLayout(RegisterForm);
        RegisterForm.setLayout(RegisterFormLayout);
        RegisterFormLayout.setHorizontalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createSequentialGroup()
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterFormLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterFormLayout.createSequentialGroup()
                                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(RegisterFormLayout.createSequentialGroup()
                                        .addComponent(Username)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userAlert))
                                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterFormLayout.createSequentialGroup()
                                        .addComponent(Username1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passAlert))
                                    .addComponent(jpSignUp)))
                            .addGroup(RegisterFormLayout.createSequentialGroup()
                                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterFormLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(BtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(BtnSignUpAsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(RegisterFormLayout.createSequentialGroup()
                                            .addComponent(school)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(univAlert))
                                        .addGroup(RegisterFormLayout.createSequentialGroup()
                                            .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(RegisterFormLayout.createSequentialGroup()
                                                    .addComponent(Username2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(courseAlert))
                                                .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(RegisterFormLayout.createSequentialGroup()
                                                    .addComponent(IDnumber)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(IDnumAlert))
                                                .addComponent(tfIDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(tfUniversity)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(RegisterFormLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Signup)
                            .addGroup(RegisterFormLayout.createSequentialGroup()
                                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegisterFormLayout.createSequentialGroup()
                                        .addComponent(FN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fNameAlert)))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(RegisterFormLayout.createSequentialGroup()
                                        .addComponent(LN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lNameAlert))
                                    .addComponent(tfLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
        );
        RegisterFormLayout.setVerticalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FN)
                    .addComponent(LN)
                    .addComponent(fNameAlert)
                    .addComponent(lNameAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username1)
                        .addComponent(userAlert)
                        .addComponent(passAlert)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpSignUp)
                    .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(school)
                    .addComponent(univAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createSequentialGroup()
                        .addComponent(Username2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createSequentialGroup()
                        .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDnumber)
                            .addComponent(courseAlert)
                            .addComponent(IDnumAlert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSignUpAsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginbgLayout = new javax.swing.GroupLayout(Loginbg);
        Loginbg.setLayout(LoginbgLayout);
        LoginbgLayout.setHorizontalGroup(
            LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginbgLayout.createSequentialGroup()
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginbgLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel11)
                    .addContainerGap(286, Short.MAX_VALUE)))
            .addGroup(LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginbgLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jLabel12)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );
        LoginbgLayout.setVerticalGroup(
            LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginbgLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel11)
                    .addContainerGap(265, Short.MAX_VALUE)))
            .addGroup(LoginbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginbgLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel12)
                    .addContainerGap(265, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastnameActionPerformed

    private void tfFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstnameActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void firstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname1ActionPerformed

    private void tfUniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUniversityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUniversityActionPerformed

    private void tfCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCourseActionPerformed

    private void tfIDnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDnumActionPerformed

    private void BtnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSigninActionPerformed
        this.userType = "COSTUMER";

        if (verifyLogin(tfUsername.getText().trim(), jpSignin.getText().trim(), userType.trim())) {
            new HomePage(getFullName()).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Login Failed!", " Alert! ", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BtnSigninActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        if (tfUsername.getText().equals("  Username")) {
            tfUsername.setText("");
            tfUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        if (tfUsername.getText().equals("")) {
            tfUsername.setText("  Username");
            tfUsername.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void jpSigninFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpSigninFocusGained
        if (jpSignin.getText().equals("Password")) {
            jpSignin.setText("");
            jpSignin.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jpSigninFocusGained

    private void jpSigninFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpSigninFocusLost
        if (jpSignin.getText().equals("")) {
            jpSignin.setText("Password");
            jpSignin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpSigninFocusLost

    private void BtnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginAdminActionPerformed
        this.userType = "ADMIN";

        if (verifyLogin(tfUsername.getText().trim(), jpSignin.getText().trim(), userType.trim())) {
            String secretcode = JOptionPane.showInputDialog(this, "Secret Code");
            if (Integer.parseInt(secretcode) == this.secretCode) {
                new AdminSystem().setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Login Failed!", " Alert! ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnLoginAdminActionPerformed

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
        this.userType = "COSTUMER";
        if (fNameAlert.getText().equals("Valid") && lNameAlert.getText().equals("Valid")
                && userAlert.getText().equals("Valid") && passAlert.getText().equals("Valid")
                && univAlert.getText().equals("Valid") && courseAlert.getText().equals("Valid")
                && IDnumAlert.getText().equals("Valid")) {
            if (!verifyLogin(tfUsername.getText().trim(), jpSignin.getText().trim(), userType.trim())) {
                if (!tfUsername.getText().equals(jpSignin.getText())
                        && (jpSignin.getText().length() > 4 || jpSignin.getText().length() < 16)) {
                    createAcc(tfUser.getText().trim(), jpSignUp.getText().trim(), userType.trim());
                    JOptionPane.showMessageDialog(this, "Signup Successful");
                    fNameAlert.setText("");
                    lNameAlert.setText("");
                    userAlert.setText("");
                    passAlert.setText("");
                    univAlert.setText("");
                    courseAlert.setText("");
                    IDnumAlert.setText("");
                    tfFirstname.setText("");
                    tfLastname.setText("");
                    tfUser.setText("");
                    jpSignUp.setText("");
                    tfUniversity.setText("");
                    tfCourse.setText("");
                    tfIDnum.setText("");
                }
            }
        } else {
            if (fNameAlert.getText().equals("*") || lNameAlert.getText().equals("*")
                    || userAlert.getText().equals("*") || passAlert.getText().equals("*")
                    || univAlert.getText().equals("*") || courseAlert.getText().equals("*")
                    || IDnumAlert.getText().equals("*")) {
                JOptionPane.showMessageDialog(this, "Fillup all the requirements!", " Alert! ", JOptionPane.WARNING_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "Sign up failed!", " Alert! ", JOptionPane.WARNING_MESSAGE);
        }
        if (false) {
            createAcc(tfUser.getText().trim(), jpSignUp.getText().trim(), userType.trim());
        }
    }//GEN-LAST:event_BtnSignUpActionPerformed

    private void BtnSignUpAsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpAsAdminActionPerformed
        this.userType = "ADMIN";

        if (fNameAlert.getText().equals("Valid") && lNameAlert.getText().equals("Valid")
                && userAlert.getText().equals("Valid") && passAlert.getText().equals("Valid")
                && univAlert.getText().equals("Valid") && courseAlert.getText().equals("Valid")
                && IDnumAlert.getText().equals("Valid")) {
            String secretcode = JOptionPane.showInputDialog(this, "Secret Code");
            if (Integer.parseInt(secretcode) == this.secretCode) {

            }
            if (!verifyLogin(tfUsername.getText().trim(), jpSignin.getText().trim(), userType.trim())) {
                if (!tfUsername.getText().equals(jpSignin.getText())
                        && (jpSignin.getText().length() > 4 || jpSignin.getText().length() < 16)) {
                    createAcc(tfUser.getText().trim(), jpSignUp.getText().trim(), userType.trim());

                    JOptionPane.showMessageDialog(this, "Signup Successful");
                    fNameAlert.setText("");
                    lNameAlert.setText("");
                    userAlert.setText("");
                    passAlert.setText("");
                    univAlert.setText("");
                    courseAlert.setText("");
                    IDnumAlert.setText("");
                    tfFirstname.setText("");
                    tfLastname.setText("");
                    tfUser.setText("");
                    jpSignUp.setText("");
                    tfUniversity.setText("");
                    tfCourse.setText("");
                    tfIDnum.setText("");
                }
            }
        } else {
            if (fNameAlert.getText().equals("*") || lNameAlert.getText().equals("*")
                    || userAlert.getText().equals("*") || passAlert.getText().equals("*")
                    || univAlert.getText().equals("*") || courseAlert.getText().equals("*")
                    || IDnumAlert.getText().equals("*")) {
                JOptionPane.showMessageDialog(this, "Fillup all the requirements!", " Alert! ", JOptionPane.WARNING_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "Sign up failed!", " Alert! ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnSignUpAsAdminActionPerformed

    private void tfFirstnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfFirstnameInputMethodTextChanged
    }//GEN-LAST:event_tfFirstnameInputMethodTextChanged

    private void tfFirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstnameKeyPressed

        if (tfFirstname.getText().equals("") && tfFirstname.getText().matches(alphabeth)) {
            fNameAlert.setText("*");
            fNameAlert.setForeground(new Color(205, 0, 0));
        } else {
            fNameAlert.setText("Valid");
            tfFirstname.setText(tfFirstname.getText().substring(0, 1).toUpperCase()
                    + tfFirstname.getText().substring(1).toLowerCase());
            fNameAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_tfFirstnameKeyPressed

    private void tfLastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLastnameKeyPressed
        if (tfLastname.getText().equals("") && tfLastname.getText().matches(alphabeth)) {
            lNameAlert.setText("*");
            lNameAlert.setForeground(new Color(205, 0, 0));
        } else {
            lNameAlert.setText("Valid");
            tfLastname.setText(tfLastname.getText().substring(0, 1).toUpperCase()
                    + tfLastname.getText().substring(1).toLowerCase());
            lNameAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_tfLastnameKeyPressed

    private void tfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyPressed
        if (tfUser.getText().equals("")) {
            userAlert.setText("*");
            userAlert.setForeground(new Color(205, 0, 0));
        } else {
            userAlert.setText("Valid");
            userAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_tfUserKeyPressed

    private void jpSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpSignUpKeyPressed
        if (jpSignUp.getText().equals("")) {
            passAlert.setText("*");
            passAlert.setForeground(new Color(205, 0, 0));
        } else {
            passAlert.setText("Valid");
            passAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_jpSignUpKeyPressed

    private void tfUniversityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUniversityKeyPressed
        if (tfUniversity.getText().equals("")) {
            univAlert.setText("*");
            univAlert.setForeground(new Color(205, 0, 0));
        } else {
            univAlert.setText("Valid");
            univAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_tfUniversityKeyPressed

    private void tfCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCourseKeyPressed
        if (tfCourse.getText().equals("")) {
            courseAlert.setText("*");
            courseAlert.setForeground(new Color(205, 0, 0));
        } else {
            courseAlert.setText("Valid");
            courseAlert.setForeground(new Color(0, 204, 51));
        }
    }//GEN-LAST:event_tfCourseKeyPressed

    private void tfIDnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIDnumKeyPressed
        if (tfIDnum.getText().equals("") && tfIDnum.getText().matches(numbers)) {
            IDnumAlert.setText("*");
            IDnumAlert.setForeground(new Color(205, 0, 0));
        } else {
            IDnumAlert.setText("Valid");
            IDnumAlert.setForeground(new Color(0, 204, 51));
        }

    }//GEN-LAST:event_tfIDnumKeyPressed

    private void tfFirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstnameKeyReleased

    }//GEN-LAST:event_tfFirstnameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoginAdmin;
    private javax.swing.JButton BtnLoginGoogle;
    private javax.swing.JButton BtnLoginMicrosoft;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JButton BtnSignUpAsAdmin;
    private javax.swing.JButton BtnSignin;
    private javax.swing.JLabel FN;
    private javax.swing.JLabel FN1;
    private javax.swing.JLabel IDnumAlert;
    private javax.swing.JLabel IDnumber;
    private javax.swing.JLabel LN;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPanel Loginbg;
    private javax.swing.JPanel RegisterForm;
    private javax.swing.JLabel Signup;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel courseAlert;
    private javax.swing.JLabel fNameAlert;
    private javax.swing.JTextField firstname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPasswordField jpSignUp;
    private javax.swing.JPasswordField jpSignin;
    private javax.swing.JLabel lNameAlert;
    private javax.swing.JLabel passAlert;
    private javax.swing.JLabel school;
    private javax.swing.JTextField tfCourse;
    private javax.swing.JTextField tfFirstname;
    private javax.swing.JTextField tfIDnum;
    private javax.swing.JTextField tfLastname;
    private javax.swing.JTextField tfUniversity;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel univAlert;
    private javax.swing.JLabel userAlert;
    // End of variables declaration//GEN-END:variables
}
